python main.py \
--model=meta-llama/Llama-3.2-1B \
--tokenizer_check=tokenizer_3500 \
--batch_size=1 \
--pad_to_max=1020 \
--device=cuda:1 \
--peft \
--num_merges=3500 \
--checkpoint=meta-llama \
--inference \
--dataset=mimic_500 \
--percentiles=./data/mimic_dataset_stats.npy