name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: pip install --upgrade pip && pip install uv

      - name: Install package (editable) with judge extras
        run: uv pip install --system -e ".[judge]"

      - name: Smoke test import
        run: |
          python - << 'PY'
          import importlib
          import torch
          # Ensure core package imports
          importlib.import_module("ecg_bench")
          print("ecg_bench import OK; torch=", torch.__version__)
          PY